#!/usr/bin/env python3.8
import sys
from parse import *
from calc import *

def main(ac, av):
    if (ac == 3):
        between_0_200(int(av[1]), int(av[2]))
    if (ac == 4):
        inferior_iq(int(av[1]), int(av[2]), int(av[3]))
    if (ac == 5):
        between_min_max(int(av[1]), int(av[2]), int(av[3]), int(av[4]))

if __name__ == '__main__':
    check_av(len(sys.argv), sys.argv)
    main(len(sys.argv), sys.argv)
    sys.exit(0)