##
## EPITECH PROJECT, 2019
## my_makefile
## File description:
## makefile
##

all:
	make -sC ./anagram/
	make -sC ./boxerNameFormatter/
	make -sC ./clean_str/
	make -sC ./countwords/
	make -sC ./fazzbizz/
	make -sC ./fizzbuzz/
	make -sC ./fozzbazz/
	make -sC ./frenchNameFormatter/
	make -sC ./fuzzbozz/
	make -sC ./geekNameFormatter/
	make -sC ./hidenp/
	make -sC ./palindrome/
	make -sC ./rostring/
	make -sC ./rrostring/
	make -sC ./sort_words/
	make -sC ./USNameFormatter/

clean:
	make clean -sC ./anagram/
	make clean -sC ./boxerNameFormatter/
	make clean -sC ./clean_str/
	make clean -sC ./countwords/
	make clean -sC ./fazzbizz/
	make clean -sC ./fizzbuzz/
	make clean -sC ./fozzbazz/
	make clean -sC ./frenchNameFormatter/
	make clean -sC ./fuzzbozz/
	make clean -sC ./geekNameFormatter/
	make clean -sC ./hidenp/
	make clean -sC ./palindrome/
	make clean -sC ./rostring/
	make clean -sC ./rrostring/
	make clean -sC ./sort_words/
	make clean -sC ./USNameFormatter/

fclean:	clean
	make fclean -sC ./anagram/
	make fclean -sC ./boxerNameFormatter/
	make fclean -sC ./clean_str/
	make fclean -sC ./countwords/
	make fclean -sC ./fazzbizz/
	make fclean -sC ./fizzbuzz/
	make fclean -sC ./fozzbazz/
	make fclean -sC ./frenchNameFormatter/
	make fclean -sC ./fuzzbozz/
	make fclean -sC ./geekNameFormatter/
	make fclean -sC ./hidenp/
	make fclean -sC ./palindrome/
	make fclean -sC ./rostring/
	make fclean -sC ./rrostring/
	make fclean -sC ./sort_words/
	make fclean -sC ./USNameFormatter/

re:	fclean all