#!/usr/bin/env python3.8
import sys
from parse import *
from derivation import titration

def main(ac, av):
    check_av(ac, av)
    data = load_file_in_mem(av)
    titration(data)

if __name__ == '__main__':
    main(len(sys.argv), sys.argv)
    sys.exit(0)