#!/usr/bin/env python3.8
import sys
from parse import *
from calc import *

def display(n, std, a, r, h):
    print("\tNumber of values:\t%d" % n)
    print("\tStandard deviation:\t%.2f" % std)
    print("\tArithmetic mean:\t%.2f" % a)
    print("\tRoot mean square:\t%.2f" % r)
    print("\tHarmonic mean:\t\t%.2f\n" % h)

def main(n, a, h, std):
    try:
        value = input("Enter next value: ")
        if is_str_float(value) == True:
           value = float(value)
           if value <= 0:
              sys.exit(84)
           new_art = art_mean(value, a, n, n + 1)
           new_har = har_mean(value, h, n, n + 1)
           new_std = std_mean(value, a, new_art, std, n, n + 1)
           rt_mean = root_mean(new_art, new_std)
           display(n + 1, new_std, new_art, rt_mean, new_har)
           main (n + 1, new_art, new_har, new_std)
        elif value == "END":
           sys.exit(0)
        else:
           sys.exit (84)
    except EOFError:
           sys.exit(84)
    except KeyboardInterrupt:
           sys.exit(84)

if __name__ == '__main__':
    av, ac = sys.argv, len(sys.argv)
    check_av(ac, av)
    n, a, h, std = float(av[1]), float(av[2]), float(av[3]), float(av[4])
    main(n, a, h, std)
    sys.exit(0)
