#!/usr/bin/env python3.8
import sys
from parse import *
from perform_action import *

def main(ac, av):
    if (ac == 2):
        d = int(av[1])
        print('Binomial distribution:')
        binomial_law(d)
        print('\nPoisson distribution:')
        poisson_law(d)
    elif (ac == 3):
        n = int(av[1])
        k = int(av[2])
        print('%d-combinations of a set of size %d:' % (k, n))
        print(binomial(n, k))

if __name__ == '__main__':
    check_av(len(sys.argv), sys.argv)
    main(len(sys.argv), sys.argv)
    sys.exit(0)