#!/usr/bin/env python3.8
import sys
from parse import *
from calc import *
from get import *

def display_countries(countries):
    print("Country: ", end="")
    for country in range(0, len(countries)):
        print(countries[country][0], end="")
        print(", ", end="") if (country != len(countries) - 1) else print("")

def main(ac, av):
    countries = get_file_content("207demography_data.csv", av)
    display_countries(countries)
    compute(get_population(countries))

if __name__ == '__main__':
    av, ac = sys.argv, len(sys.argv)
    check_av(ac, av)
    main(ac, av)
    sys.exit(0)