##
## EPITECH PROJECT, 2019
## my_makefile
## File description:
## makefile
##

all:
	@make -sC asm/
	@make -sC corewar/

clean:
	@make clean -sC asm/
	@make clean -sC corewar/

fclean:	clean
	@make fclean -sC asm/
	@make fclean -sC corewar/

re:	fclean all