#!/usr/bin/env python3.8
import sys
from math import sqrt
from parse import *
from calc import *

def main(av):
    variance = get_variance(av)
    result1 = (2 * 1.96 * sqrt(variance)) / 2 * 100
    result2 = (2 * 2.58 * sqrt(variance)) / 2 * 100
    print("Population size: \t\t", av[1])
    print("Sample size:\t\t\t", av[2])
    print("Voting intentions: \t\t", av[3], end="")
    print("%")
    print("Variance:\t\t\t %.6f" % variance)
    print("95% confidence interval:\t [", end="")
    print("%.2f" % get_min(float(av[3]) - result1), end="")
    print("%; ", end="")
    print("%.2f" % get_max(float(av[3]) + result1), end="")
    print("%]")
    print("99% confidence interval:\t [", end="")
    print("%.2f" %  get_min(float(av[3]) - result2), end="")
    print("%; ", end="")
    print("%.2f" % get_max(float(av[3]) + result2), end="")
    print("%]")

if __name__ == '__main__':
    av, ac = sys.argv, len(sys.argv)
    check_av(ac, av)
    main(av)
    sys.exit(0)