#!/usr/bin/env python3.8
import sys
from parse import *
from calcul import *

def main(ac, av):
    check_av(ac, av)
    n = float(av[1])
    b = 5000
    k = 10000
    h = 0.5
    midpoint(n, b, k, h)
    trapezoidal(n, b, k, h)
    simpson(n, b, k, h)

if __name__ == '__main__':
    main(len(sys.argv), sys.argv)
    sys.exit(0)