##
## EPITECH PROJECT, 2019
## my_makefile
## File description:
## makefile
##

all:
	make -s -C sfml/
	make -s -C ncurse/

clean:
	make clean -s -C ncurse/
	make clean -s -C sfml/

fclean:	clean
	make fclean -s -C sfml/
	make fclean -s -C ncurse/

re:	fclean all